// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Data;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            ManufacturerId = 1,
                            Model = "Camry",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Ford",
                            ManufacturerId = 2,
                            Model = "Mustang",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            ManufacturerId = 3,
                            Model = "X5",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.CarEngine", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CarId", "EngineId");

                    b.HasIndex("EngineId");

                    b.ToTable("CarEngines");
                });

            modelBuilder.Entity("WebApplication3.Models.CarProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("CarProfiles");
                });

            modelBuilder.Entity("WebApplication3.Models.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HorsePower = 301,
                            Type = "V6"
                        },
                        new
                        {
                            Id = 2,
                            HorsePower = 450,
                            Type = "V8"
                        },
                        new
                        {
                            Id = 3,
                            HorsePower = 335,
                            Type = "Inline-6"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Japan",
                            Description = "Japanese automotive manufacturer",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Description = "American automotive manufacturer",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            Description = "German luxury automotive manufacturer",
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.Car", b =>
                {
                    b.HasOne("WebApplication3.Models.Manufacturer", "Manufacturer")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("WebApplication3.Models.CarEngine", b =>
                {
                    b.HasOne("WebApplication3.Models.Car", "Car")
                        .WithMany("CarEngines")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Engine", "Engine")
                        .WithMany("CarEngines")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("WebApplication3.Models.CarProfile", b =>
                {
                    b.HasOne("WebApplication3.Models.Car", "Car")
                        .WithOne("CarProfile")
                        .HasForeignKey("WebApplication3.Models.CarProfile", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("WebApplication3.Models.Car", b =>
                {
                    b.Navigation("CarEngines");

                    b.Navigation("CarProfile");
                });

            modelBuilder.Entity("WebApplication3.Models.Engine", b =>
                {
                    b.Navigation("CarEngines");
                });

            modelBuilder.Entity("WebApplication3.Models.Manufacturer", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
